/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.smart_parking_app;

/**
 *
 * @author ABC
 */
public class SmartParkingAppGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SmartParkingAppGUI.class.getName());
    ParkingManager myParkingManager = new ParkingManager();
    
    
    /**
     * Creates new form SmartParkingAppGUI
     */
    public SmartParkingAppGUI() {
        initComponents();
        availableSpotCounts();
        
        
        // make these field uneditable
        jTextFieldForAvailabeNormalParkingSpaces.setEditable(false);
        jTextFieldForAvailabeNormalParkingSpaces.setFocusable(false);
        jTextFieldForAvailablePriorityParkingSpaces.setEditable(false);
        jTextFieldForAvailablePriorityParkingSpaces.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupForCarType = new javax.swing.ButtonGroup();
        buttonGroupForDisability = new javax.swing.ButtonGroup();
        buttonGroupForParkingType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldForPlateNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonForElectronic = new javax.swing.JRadioButton();
        jRadioButtonForNonElectronic = new javax.swing.JRadioButton();
        jRadioButtonForDisability = new javax.swing.JRadioButton();
        jRadioButtonForNonDisability = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonForParkingTypeNormal = new javax.swing.JRadioButton();
        jRadioButtonForParkingTypePriority = new javax.swing.JRadioButton();
        jButtonForSubmit = new javax.swing.JButton();
        jTextFieldForAvailabeNormalParkingSpaces = new javax.swing.JTextField();
        jTextFieldForAvailablePriorityParkingSpaces = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaForDisplaying = new javax.swing.JTextArea();
        jButtonForListOfNormalParking = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Smart Parking App");

        jLabel2.setText("Plate Number:");

        jTextFieldForPlateNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForPlateNumberActionPerformed(evt);
            }
        });

        jLabel3.setText("Car Type:");

        jLabel4.setText("Disability:");

        buttonGroupForCarType.add(jRadioButtonForElectronic);
        jRadioButtonForElectronic.setText("Electronic");
        jRadioButtonForElectronic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonForElectronicActionPerformed(evt);
            }
        });

        buttonGroupForCarType.add(jRadioButtonForNonElectronic);
        jRadioButtonForNonElectronic.setText("Non-Electonic");

        buttonGroupForDisability.add(jRadioButtonForDisability);
        jRadioButtonForDisability.setText("Yes");
        jRadioButtonForDisability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonForDisabilityActionPerformed(evt);
            }
        });

        buttonGroupForDisability.add(jRadioButtonForNonDisability);
        jRadioButtonForNonDisability.setText("No");

        jLabel5.setText("Availabe Normal Parking Spaces: ");

        jLabel6.setText("Available Priority Parking Spaces:");

        jLabel7.setText("Parking type: ");

        buttonGroupForParkingType.add(jRadioButtonForParkingTypeNormal);
        jRadioButtonForParkingTypeNormal.setText("Normal");

        buttonGroupForParkingType.add(jRadioButtonForParkingTypePriority);
        jRadioButtonForParkingTypePriority.setText("Priority");

        jButtonForSubmit.setText("Submit");
        jButtonForSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForSubmitActionPerformed(evt);
            }
        });

        jTextFieldForAvailabeNormalParkingSpaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForAvailabeNormalParkingSpacesActionPerformed(evt);
            }
        });

        jTextAreaForDisplaying.setColumns(20);
        jTextAreaForDisplaying.setRows(5);
        jScrollPane1.setViewportView(jTextAreaForDisplaying);

        jButtonForListOfNormalParking.setText("list of normarl parking");
        jButtonForListOfNormalParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForListOfNormalParkingActionPerformed(evt);
            }
        });

        jButton2.setText("list of priority parking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jButtonForListOfNormalParking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldForPlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonForElectronic)
                            .addComponent(jRadioButtonForDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonForNonDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonForNonElectronic, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonForParkingTypeNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonForSubmit)
                            .addComponent(jRadioButtonForParkingTypePriority, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldForAvailablePriorityParkingSpaces, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldForAvailabeNormalParkingSpaces, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldForPlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldForAvailabeNormalParkingSpaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonForElectronic)
                        .addComponent(jRadioButtonForNonElectronic)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldForAvailablePriorityParkingSpaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonForDisability)
                                .addComponent(jRadioButtonForNonDisability)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonForParkingTypeNormal)
                                .addComponent(jRadioButtonForParkingTypePriority)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonForSubmit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonForListOfNormalParking)
                    .addComponent(jButton2))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonForElectronicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonForElectronicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonForElectronicActionPerformed

    private void jRadioButtonForDisabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonForDisabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonForDisabilityActionPerformed

    private void jTextFieldForPlateNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForPlateNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldForPlateNumberActionPerformed

    private void jButtonForSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForSubmitActionPerformed
        // TODO add your handling code here:
        String plateNumber = jTextFieldForPlateNumber.getText();
        boolean disability = jRadioButtonForDisability.isSelected();
        Vehicle temp = null;
        
        // check car type
        if(jRadioButtonForElectronic.isSelected()) {
            temp = new ElectronicVehicle(plateNumber, disability, "electronic");
        }
        else if(jRadioButtonForNonElectronic.isSelected()) {
            temp = new NonElectronicVehicle(plateNumber, disability, "non-electronic");
        }
        
        // check parking type
        if(jRadioButtonForParkingTypeNormal.isSelected()) {
            myParkingManager.normalEnqueue(temp);
        }
        else if(jRadioButtonForParkingTypePriority.isSelected()) {
            
        }
        
        availableSpotCounts();
    }//GEN-LAST:event_jButtonForSubmitActionPerformed

    private void jTextFieldForAvailabeNormalParkingSpacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForAvailabeNormalParkingSpacesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldForAvailabeNormalParkingSpacesActionPerformed

    private void jButtonForListOfNormalParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForListOfNormalParkingActionPerformed
        // TODO add your handling code here:
        jTextAreaForDisplaying.setText(myParkingManager.getDetailedInformationOfReservedParkingSpots());
    }//GEN-LAST:event_jButtonForListOfNormalParkingActionPerformed

    
    private void availableSpotCounts() {
        int normalParking = myParkingManager.getAvailabeNormalParkingSpots();
        int priorityParking = myParkingManager.getAvaiablePriorityParkingSpots();
        
        jTextFieldForAvailabeNormalParkingSpaces.setText(String.valueOf(normalParking));
        jTextFieldForAvailablePriorityParkingSpaces.setText(String.valueOf(priorityParking));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SmartParkingAppGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupForCarType;
    private javax.swing.ButtonGroup buttonGroupForDisability;
    private javax.swing.ButtonGroup buttonGroupForParkingType;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonForListOfNormalParking;
    private javax.swing.JButton jButtonForSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButtonForDisability;
    private javax.swing.JRadioButton jRadioButtonForElectronic;
    private javax.swing.JRadioButton jRadioButtonForNonDisability;
    private javax.swing.JRadioButton jRadioButtonForNonElectronic;
    private javax.swing.JRadioButton jRadioButtonForParkingTypeNormal;
    private javax.swing.JRadioButton jRadioButtonForParkingTypePriority;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaForDisplaying;
    private javax.swing.JTextField jTextFieldForAvailabeNormalParkingSpaces;
    private javax.swing.JTextField jTextFieldForAvailablePriorityParkingSpaces;
    private javax.swing.JTextField jTextFieldForPlateNumber;
    // End of variables declaration//GEN-END:variables
}
